### ISSUE TITLE
hi,I have a problem. Can you help me solve it? Thank you.

### ISSUE THREAD

**Issue by ChenCongZ** [cfrioux/MeneTools#10]
import
logging
logging.basicConfig（） from metage2metabo.m2m
import individual_scope individual_scope.iscope（'community'，'seeds.sbml'，'output_folder'）
SBML 文件中的语法无效： community\OrgA.sbml
---------------Something 在 OrgA 上运行 Menetools 时
出错--------------- SBML 文件中的语法无效： community\OrgB.sbml
---------------在 OrgB 上运行 Menetools 时
出错--------------- SBML 文件中的语法无效： community\OrgC.sbml
---------------在 OrgC 上运行 Menetools 时出错---------------
CRITICAL：metage2metabo.m2m.individual_scope：------------在 M2M 运行 Menetools 期间发生错误，M2M 将停止-------------

@cfrioux

**Comment by cfrioux** [comment]
Could you give more information please? What OS are you using, what versions of MeneTools and Metage2Metabo?
Also could you please send the full log?
I could not reproduce the error. 
```
>>> from metage2metabo.m2m import individual_scope
>>> individual_scope.iscope(out_dir="~/wd/zzz/testiscope",seeds='seeds.xml',cpu_number=1,sbmldir="symbionts")
{'a', 'b', 'd', 'e', 'c'}
```

**Comment by ChenCongZ** [comment]
> 您能提供更多信息吗？您使用的是哪种操作系统，MeneTools和Metage2Metabo的哪个版本？另外，您能发送完整的日志吗？我无法重现错误。
> 
> ```
> >>> from metage2metabo.m2m import individual_scope
> >>> individual_scope.iscope(out_dir="~/wd/zzz/testiscope",seeds='seeds.xml',cpu_number=1,sbmldir="symbionts")
> {'a', 'b', 'd', 'e', 'c'}
> ```

Thank you, I have solved this problem. but I met the next question. 
 import json
>>> with open('output_folder/indiv_scopes/indiv_scopes.json') as iscope_output:
...     iscope_json_data = json.load(iscope_output)
... print('Individual scope:')

  File "<stdin>", line 3
    print('Individual scope:')
    ^^^^^
SyntaxError: invalid syntax
I cannot enter the second print.

**Comment by ChenCongZ** [comment]
> 

menetools == 3.2.0 metage2metabo == 1.5.0

**Comment by ChenCongZ** [comment]
> Could you give more information please? What OS are you using, what versions of MeneTools and Metage2Metabo? Also could you please send the full log? I could not reproduce the error.
> 
> ```
> >>> from metage2metabo.m2m import individual_scope
> >>> individual_scope.iscope(out_dir="~/wd/zzz/testiscope",seeds='seeds.xml',cpu_number=1,sbmldir="symbionts")
> {'a', 'b', 'd', 'e', 'c'}
> ```

Excuse me, can you enter this command? Let me see the result. I can't get the result after I enter it.
import json

with open('output_folder/indiv_scopes/indiv_scopes.json') as iscope_output:
    iscope_json_data = json.load(iscope_output)

print('Individual scope:')

print('{0}: {1} metabolites ({2}).'.format('OrgA', len(iscope_json_data['OrgA']), ', '.join(sorted(iscope_json_data['OrgA']))))

**Comment by ChenCongZ** [comment]
> 

Can you show me a screenshot of your input command? I think it may be a mistake when I input it.

**Comment by ChenCongZ** [comment]
> 我刚刚发现你正在运行metage2metabo的教程。
> 
> 我仍然无法重现错误。我使用相同版本的MeneTools和M2M。
> 
> 来自笔记本的单元格输入 4 为我提供以下输出：
> 
> ```
> Individual scope:
> OrgA: 4 metabolites (M_A_c, M_B_c, M_D_c, M_F_c).
> ```
> 
> 在运行笔记本之前，是否修改了笔记本的代码？您是否从目录中启动？`jupyter notebook``metage2metabo/tutorials/method_tutorial`

I didn't modify the code and run it in the directory.

**Comment by ChenCongZ** [comment]
> 我刚刚发现你正在运行metage2metabo的教程。
> 
> 我仍然无法重现错误。我使用相同版本的MeneTools和M2M。
> 
> 来自笔记本的单元格输入 4 为我提供以下输出：
> 
> ```
> Individual scope:
> OrgA: 4 metabolites (M_A_c, M_B_c, M_D_c, M_F_c).
> ```
> 
> 在运行笔记本之前，是否修改了笔记本的代码？您是否从目录中启动？`jupyter notebook``metage2metabo/tutorials/method_tutorial`

Thanks, I have solved it.

**Comment by ChenCongZ** [comment]
> 我刚刚发现你正在运行metage2metabo的教程。
> 
> 我仍然无法重现错误。我使用相同版本的MeneTools和M2M。
> 
> 来自笔记本的单元格输入 4 为我提供以下输出：
> 
> ```
> Individual scope:
> OrgA: 4 metabolites (M_A_c, M_B_c, M_D_c, M_F_c).
> ```
> 
> 在运行笔记本之前，是否修改了笔记本的代码？您是否从目录中启动？`jupyter notebook``metage2metabo/tutorials/method_tutorial`

 from metage2metabo.m2m import community_scope
>>> instance_path, network_scopes = community_scope.cscope('community', 'seeds.sbml', 'output_folder')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\陈聪聪\AppData\Roaming\Python\Python310\site-packages\metage2metabo\m2m\community_scope.py", line 50, in cscope
    community_reachable_metabolites = comm_scope_run(instance_com, out_dir, host)
  File "C:\Users\陈聪聪\AppData\Roaming\Python\Python310\site-packages\metage2metabo\m2m\community_scope.py", line 108, in comm_scope_run
    microbiota_scope = run_scopes(lp_instance_file=instance)
  File "C:\Users\陈聪聪\AppData\Roaming\Python\Python310\site-packages\miscoto\miscoto_scopes.py", line 171, in run_scopes
    model = query.get_scopes(lp_instance_file, commons.ASP_SRC_SCOPES)
  File "C:\Users\陈聪聪\AppData\Roaming\Python\Python310\site-packages\miscoto\query.py", line 34, in get_scopes
    for model in models.discard_quotes.by_arity:
  File "C:\Program Files\Python310\lib\site-packages\clyngor\answers.py", line 205, in __iter__
    for answer_set, optimization, optimality, answer_number in self._answers:
  File "C:\Program Files\Python310\lib\site-packages\clyngor\solving.py", line 231, in _gen_answers
    for payload in validate_clasp_stderr(stderr):
  File "C:\Program Files\Python310\lib\site-packages\clyngor\parsing.py", line 244, in validate_clasp_stderr
    line = next(stderr).strip()
  File "C:\Program Files\Python310\lib\site-packages\clyngor\solving.py", line 115, in <genexpr>
    stderr = (line.decode() for line in clingo.stderr)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb3 in position 9: invalid start byte.
How to solve this problem? Thank you!

**Comment by ArnaudBelcour** [comment]
Hi @ChenCongZ,

From your log, I think the issue is that the line:

`stderr = (line.decode() for line in clingo.stderr)`

expects a 'utf-8' encoding whereas the byte '0xb3' seems to be encode in 'ascii' (according to [chardet detect](https://chardet.readthedocs.io/en/latest/usage.html#example-using-the-detect-function)).

One way to solve this will be to set the encoding as 'utf-8'. For this you can maybe used the variable [PYTHONIOENCODING](https://docs.python.org/3.6/using/cmdline.html#envvar-PYTHONIOENCODING) before entering your python terminal. Something like this:

`PYTHONIOENCODING=UTF-8 python3`

**Comment by ChenCongZ** [comment]
> 嗨@ChenCongZ，
> 
> 从您的日志中，我认为问题在于该行：
> 
> `stderr = (line.decode() for line in clingo.stderr)`
> 
> 期望"utf-8"编码，而字节"0xb3"似乎编码为"ascii"（根据[chardet检测](https://chardet.readthedocs.io/en/latest/usage.html#example-using-the-detect-function)）。
> 
> 解决此问题的一种方法是将编码设置为"utf-8"。为此，您可以在进入python终端之前使用变量[PYTHONIOENCODING](https://docs.python.org/3.6/using/cmdline.html#envvar-PYTHONIOENCODING)。像这样：
> 
> `PYTHONIOENCODING=UTF-8 python3`

Enter the command to get the following results.
D:\Metage2Metabo\method_tutorial>set PYTHONIOENCODING=UTF-8 python3

D:\Metage2Metabo\method_tutorial>py -3
Fatal Python error: init_stdio_encoding: failed to get the Python codec name of the stdio encoding
Python runtime state: core initialized
LookupError: unknown encoding: UTF-8 python3

Current thread 0x00000d20 (most recent call first):
  <no Python frame>
D:\Metage2Metabo\method_tutorial>

**Comment by ChenCongZ** [comment]
> > 嗨@ChenCongZ，
> > 从您的日志中，我认为问题在于该行：
> > `stderr = (line.decode() for line in clingo.stderr)`
> > 期望"utf-8"编码，而字节"0xb3"似乎编码为"ascii"（根据[chardet检测](https://chardet.readthedocs.io/en/latest/usage.html#example-using-the-detect-function)）。
> > 解决此问题的一种方法是将编码设置为"utf-8"。为此，您可以在进入python终端之前使用变量[PYTHONIOENCODING](https://docs.python.org/3.6/using/cmdline.html#envvar-PYTHONIOENCODING)。像这样：
> > `PYTHONIOENCODING=UTF-8 python3`
> 
> 输入命令以获取以下结果。 D：\Metage2Metabo\method_tutorial>set PYTHONIOENCODING=UTF-8 python3
> 
> D：\Metage2Metabo\method_tutorial>py -3 致命 Python 错误： init_stdio_encoding： 无法获取 python 编解码器名称的 stdio 编码 Python 运行时状态： 核心初始化 查找错误： 未知编码： UTF-8 python3
> 
> 当前线程0x00000d20（最近调用优先）： D：\Metage2Metabo\method_tutorial>

@cfrioux

**Comment by ChenCongZ** [comment]
> 嗨@ChenCongZ，
> 
> 从您的日志中，我认为问题在于该行：
> 
> `stderr = (line.decode() for line in clingo.stderr)`
> 
> 期望"utf-8"编码，而字节"0xb3"似乎编码为"ascii"（根据[chardet检测](https://chardet.readthedocs.io/en/latest/usage.html#example-using-the-detect-function)）。
> 
> 解决此问题的一种方法是将编码设置为"utf-8"。为此，您可以在进入python终端之前使用变量[PYTHONIOENCODING](https://docs.python.org/3.6/using/cmdline.html#envvar-PYTHONIOENCODING)。像这样：
> 
> `PYTHONIOENCODING=UTF-8 python3`

Thank you, I have solved the problem!
