### ISSUE TITLE
The result can't be output! ! !

### ISSUE THREAD

**Issue by ChenCongZ** [cfrioux/MeneTools#11]
if len(addedvalue):
...     sbml_management.create_species_sbml(addedvalue, target_path)
... instance_mincom = community_scope.instance_community(networks_path, seeds_path, output_folder, target_path)
  File "<stdin>", line 3
    instance_mincom = community_scope.instance_community(networks_path, seeds_path, output_folder, target_path)
    ^^^^^^^^^^^^^^^
SyntaxError: invalid syntax

**Comment by cfrioux** [comment]
Hi,
Again, without context I cannot much help you...
Are you still working with the notebook? Which python, which OS, which type of env...? I need information in order to get a chance to reproduce the issue.

**Comment by cfrioux** [comment]
I'm assuming you copy paste lines from the metage2metabo tutorial? (btw this is not the good repository for the issue). 
A first error is the indentation you use for the third line, that should be:

```
if len(addedvalue):
    sbml_management.create_species_sbml(addedvalue, target_path)
instance_mincom = community_scope.instance_community(networks_path, seeds_path, output_folder, target_path)
```
not:
```
if len(addedvalue):
    sbml_management.create_species_sbml(addedvalue, target_path)
    instance_mincom = community_scope.instance_community(networks_path, seeds_path, output_folder, target_path)
```

If you have data for tests, you can also directly call `m2m` [commands](https://metage2metabo.readthedocs.io/en/latest/command.html) from the terminal, not the python console.

**Comment by ChenCongZ** [comment]
> if len(addedvalue):
> ... sbml_management.create_species_sbml(addedvalue, target_path)
> ... instance_mincom = community_scope.instance_community(networks_path, seeds_path, output_folder, target_path)
> File "", line 3
> instance_mincom = community_scope.instance_community(networks_path, seeds_path, output_folder, target_path)
> ^^^^^^^^^^^^^^^
> SyntaxError: invalid syntax
yes, My notebook, python 3.10.1, OS 22000.434 ,env D: \ Metage2metabo \ method _ tutorial >. I entered it according to your first method, but I didn't output the result and showed a syntax error.

**Comment by ChenCongZ** [comment]
>>> from metage2metabo.m2m import community_addedvalue, individual_scope, community_scope
>>> from metage2metabo import sbml_management
>>> networks_path = 'data/community/'
>>> seeds_path = 'data/seeds.sbml'
>>> output_folder = 'output_folder'
>>> target_path = 'targets.sbml'
>>> iscope_metabolites = individual_scope.iscope(networks_path, seeds_path, output_folder)
>>> instance_comscope, cscope_metabolites = community_scope.cscope(networks_path, seeds_path, output_folder)
>>> addedvalue = community_addedvalue.addedvalue(iscope_metabolites, cscope_metabolites, output_folder)
>>> if len(addedvalue):
...          sbml_management.create_species_sbml(addedvalue, target_path)
...      instance_mincom = community_scope.instance_community(networks_path, seeds_path, output_folder, target_path)
  File "<stdin>", line 3
    instance_mincom = community_scope.instance_community(networks_path, seeds_path, output_folder, target_path)
    ^^^^^^^^^^^^^^^
SyntaxError: invalid syntax

**Comment by cfrioux** [comment]
You say you enter the code, but aren't you executing the jupyter notebook itself cell by cell? 
If not, why don't you use Jupyter and are you instead pasting the code in a python console? 
I believe errors come from copying and pasting the code...

We did not test the workflow with Python 3.10 but I doubt this version would lead to syntax errors.

**Comment by ChenCongZ** [comment]
> You say you enter the code, but aren't you executing the jupyter notebook itself cell by cell? If not, why don't you use Jupyter and are you instead pasting the code in a python console? I believe errors come from copying and pasting the code...
> 
> We did not test the workflow with Python 3.10 but I doubt this version would lead to syntax errors.
Thank you very much. I have solved the problem.， and it may be due to the system.
