### ISSUE TITLE
Create a new tagged release?

### ISSUE THREAD

**Issue by raivivek** [cfrioux/MeneTools#5]
Hi, I'm trying to merge this tool into bioconda and it'd be nice to have a tagged release for the newer versions.

https://github.com/bioconda/bioconda-recipes/pull/21570

**Comment by cfrioux** [comment]
Hi, thank you very much, this is all good now [https://github.com/cfrioux/MeneTools/tree/2.0.6](https://github.com/cfrioux/MeneTools/tree/2.0.6)
